namespace OutcomeHub.Application.DTOs.Measurement;

public sealed record ScoreRecordDto(
    Guid Id,
    short AcademicYearStart,
    Guid ScoreIdentityId,
    Guid StudentId,
    string StudentCode,
    string StudentFullName,
    Guid CourseOfferingId,
    string CourseOfferingCode,
    Guid AssessmentItemId,
    string AssessmentItemName,
    Guid? RubricCriterionId,
    string? RubricCriterionCode,
    int RevisionNo,
    decimal? RawScore,
    decimal MaxScore,
    string ScoreStatus,
    Guid RecordedBy,
    DateTimeOffset RecordedAt,
    string Checksum,
    string? CorrectionReason);

public sealed record SubmitScoreRecordRequest(
    short AcademicYearStart,
    Guid ScoreDatasetId,
    Guid StudentId,
    Guid CourseOfferingId,
    Guid ProgramVersionId,
    Guid SyllabusVersionId,
    short AttemptNo,
    Guid EnrollmentId,
    Guid AssessmentItemId,
    Guid? RubricCriterionId,
    Guid? AssessmentQuestionId,
    string ScoreLevel,
    Guid OrgUnitId,
    Guid ProgramId,
    Guid CourseId,
    int RevisionNo,
    decimal? RawScore,
    decimal MaxScore,
    string ScoreStatus,
    Guid SourceSystemId,
    string SourceRecordId,
    string SourceRevision,
    Guid IngestionBatchId,
    Guid RecordedBy,
    DateTimeOffset RecordedAt,
    string Checksum,
    Guid? SupersedesId = null,
    string? CorrectionReason = null);
