<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>OutcomeHub.Application</RootNamespace>
    <AssemblyName>OutcomeHub.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OutcomeHub.Domain/OutcomeHub.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>
</Project>
